
let words ={
a: ["author", "alogance", "arguement"],
b: ["bowl", "banana", "button"],
c: ["cover", "culture", "carapult"], 
d: ["dawn", "dust", "date"],
e: ["eagle", "eight", "edge"], 
f: ["fork", "faith", "fountain"], 
g: ["group", "gate", "gold"], 
h: ["horizon", "hellowen", "hunt"], 
i: ["issue", "image", "item"], 
j: ["jaw", "job", "jam"], 
k: ["key", "kid", "knife"], 
l: ["lamp", "ladder", "leaf"], 
m: ["map", "man", "mark"], 
n: ["nut", "nap", "null"], 
o: ["output", "oak", "oil"], 
p: ["pool", "pork", "pear"], 
q: ["question", "queen", "quote"], 
r: ["roof", "rain", "rail"], 
s: ["snake", "sword", "saint"], 
t: ["torch", "trumpet", "tape"], 
u: ["umbrella", "unicorn", "uniform"], 
v: ["velocity", "vacation", "value"], 
w: ["war", "wall", "violin"], 
x: ["xylophone", "xerox", "xerus"], 
y: ["yo-yo", "yak", "yarn"],
z: ["zero", "zebra", "zip"]
} 